local function setup(configs)
    local colors = configs.colors
    local endOfBuffer = {
        fg = configs.show_end_of_buffer and colors.begonia or colors.dominant,
    }

    return {
        Normal = { fg = colors.tufts_blue, bg = colors.dominant, },
        NormalFloat = { fg = colors.tufts_blue, bg = colors.dominant, },
        Comment = { fg = colors.pale_cerulean, italic = configs.italic_comment, },
        Constant = { fg = colors.banana_yellow, },
        String = { fg = colors.banana_yellow, },
        Character = { fg = colors.ufo_green, },
        Number = { fg = colors.cadmium_orange, },
        Boolean = { fg = colors.tufts_blue, },
        Float = { fg = colors.cadmium_orange, },
        FloatBorder = { fg = colors.baby_powder, },
        Operator = { fg = colors.violet_blue, },
        Keyword = { fg = colors.tufts_blue, },
        Keywords = { fg = colors.tufts_blue, },
        Identifier = { fg = colors.tufts_blue, },
        Function = { fg = colors.banana_yellow, },
        Statement = { fg = colors.violet_blue, },
        Conditional = { fg = colors.paradise_pink, },
        Repeat = { fg = colors.paradise_pink, },
        Label = { fg = colors.tufts_blue, },
        Exception = { fg = colors.violet_blue, },
        PreProc = { fg = colors.banana_yellow, },
        Include = { fg = colors.violet_blue, },
        Define = { fg = colors.violet_blue, },
        Title = { fg = colors.tufts_blue, },
        Macro = { fg = colors.violet_blue, },
        PreCondit = { fg = colors.tufts_blue, },
        Type = { fg = colors.tufts_blue, },
        StorageClass = { fg = colors.paradise_pink, },
        Structure = { fg = colors.banana_yellow, },
        TypeDef = { fg = colors.banana_yellow, },
        Special = { fg = colors.ufo_green, italic = true },
        SpecialComment = { fg = colors.pale_cerulean, italic = true, },
        Error = { fg = colors.english_red, },
        Todo = { fg = colors.violet_blue, bold = true, italic = true, },
        Underlined = { fg = colors.tufts_blue, underline = true, },
        Cursor = { reverse = true, },
        CursorLineNr = { fg = colors.tufts_blue, bold = true, },
        SignColumn = { bg = colors.dominant, },
        Conceal = { fg = colors.pale_cerulean, },
        CursorColumn = { bg = colors.dark_gunmetal, },
        CursorLine = { bg = colors.selection, },
        ColorColumn = { bg = colors.selection, },
        StatusLine = { fg = colors.baby_powder, bg = colors.dark_gunmetal, },
        StatusLineNC = { fg = colors.pale_cerulean, },
        StatusLineTerm = { fg = colors.baby_powder, bg = colors.dark_gunmetal, },
        StatusLineTermNC = { fg = colors.pale_cerulean, },
        Directory = { fg = colors.tufts_blue, },
        DiffAdd = { fg = colors.dominant, bg = colors.ufo_green, },
        DiffChange = { fg = colors.cadmium_orange, },
        DiffDelete = { fg = colors.cinnabar, },
        DiffText = { fg = colors.pale_cerulean, },
        ErrorMsg = { fg = colors.english_red, },
        VertSplit = { fg = colors.dark_gunmetal, },
        Folded = { fg = colors.pale_cerulean, },
        FoldColumn = {},
        Search = { fg = colors.dark_gunmetal, bg = colors.cadmium_orange, },
        IncSearch = { fg = colors.cadmium_orange, bg = colors.pale_cerulean, },
        LineNr = { fg = colors.pale_cerulean, },
        MatchParen = { fg = colors.tufts_blue, underline = true, },
        NonText = { fg = colors.nontext, },
        Pmenu = { fg = colors.baby_powder, bg = colors.menu, },
        PmenuSel = { fg = colors.baby_powder, bg = colors.selection, },
        PmenuSbar = { bg = colors.dominant, },
        PmenuThumb = { bg = colors.selection, },
        Question = { fg = colors.violet_blue, },
        QuickFixLine = { fg = colors.dark_gunmetal, bg = colors.banana_yellow, },
        SpecialKey = { fg = colors.nontext, },
        SpellBad = { fg = colors.english_red, underline = true, },
        SpellCap = { fg = colors.banana_yellow, },
        SpellLocal = { fg = colors.banana_yellow, },
        SpellRare = { fg = colors.banana_yellow, },
        TabLine = { fg = colors.pale_cerulean, },
        TabLineSel = { fg = colors.baby_powder, },
        TabLineFill = { bg = colors.dominant, },
        Terminal = { fg = colors.baby_powder, bg = colors.dark_gunmetal, },
        Visual = { bg = colors.visual, },
        VisualNOS = { fg = colors.visual, },
        WarningMsg = { fg = colors.banana_yellow, },
        WildMenu = { fg = colors.dark_gunmetal, bg = colors.baby_powder, },
        EndOfBuffer = endOfBuffer,
        -- TreeSitter
        ['@error'] = { fg = colors.english_red, },
        ['@punctuation.delimiter'] = { fg = colors.tufts_blue, },
        ['@punctuation.bracket'] = { fg = colors.tufts_blue, },
        ['@punctuation.special'] = { fg = colors.tufts_blue, },
        ['@constant'] = { fg = colors.violet_blue, },
        ['@constant.builtin'] = { fg = colors.violet_blue, },
        ['@symbol'] = { fg = colors.violet_blue, },
        ['@constant.macro'] = { fg = colors.tufts_blue, },
        ['@string.regex'] = { fg = colors.cinnabar, },
        ['@string'] = { fg = colors.banana_yellow, },
        ['@string.escape'] = { fg = colors.tufts_blue, },
        ['@character'] = { fg = colors.ufo_green, },
        ['@number'] = { fg = colors.violet_blue, },
        ['@boolean'] = { fg = colors.violet_blue, },
        ['@float'] = { fg = colors.ufo_green, },
        ['@annotation'] = { fg = colors.banana_yellow, },
        ['@attribute'] = { fg = colors.tufts_blue, },
        ['@namespace'] = { fg = colors.cadmium_orange, },
        ['@function.builtin'] = { fg = colors.tufts_blue, },
        ['@function'] = { fg = colors.ufo_green, },
        ['@function.macro'] = { fg = colors.ufo_green, },
        ['@parameter'] = { fg = colors.cadmium_orange, },
        ['@parameter.reference'] = { fg = colors.cadmium_orange, },
        ['@method'] = { fg = colors.ufo_green, },
        ['@field'] = { fg = colors.cadmium_orange, },
        ['@property'] = { fg = colors.violet_blue, },
        ['@constructor'] = { fg = colors.tufts_blue, },
        ['@conditional'] = { fg = colors.paradise_pink, },
        ['@repeat'] = { fg = colors.paradise_pink, },
        ['@label'] = { fg = colors.tufts_blue, },
        ['@keyword'] = { fg = colors.begonia, },
        ['@keyword.function'] = { fg = colors.begonia, bold = true, },
        ['@keyword.operator'] = { fg = colors.paradise_pink, },
        ['@operator'] = { fg = colors.paradise_pink, },
        ['@exception'] = { fg = colors.violet_blue, },
        ['@type'] = { fg = colors.tufts_blue,bold = true, italic = true,},
        ['@type.builtin'] = { fg = colors.tufts_blue, italic = true, },
        ['@type.qualifier'] = { fg = colors.paradise_pink, },
        ['@structure'] = { fg = colors.violet_blue, },
        ['@include'] = { fg = colors.paradise_pink, },
        ['@variable'] = { fg = colors.tufts_blue, },
        ['@variable.builtin'] = { fg = colors.violet_blue, },
        ['@text'] = { fg = colors.cadmium_orange, },
        ['@text.strong'] = { fg = colors.cadmium_orange, bold = true, }, -- bold
        ['@text.emphasis'] = { fg = colors.banana_yellow, italic = true, }, -- italic
        ['@text.underline'] = { fg = colors.cadmium_orange, },
        ['@text.title'] = { fg = colors.paradise_pink, bold = true, }, -- title
        ['@text.literal'] = { fg = colors.banana_yellow, }, -- inline code
        ['@text.uri'] = { fg = colors.banana_yellow, italic = true, }, -- urls
        ['@text.reference'] = { fg = colors.cadmium_orange, bold = true, },
        ['@tag'] = { fg = colors.tufts_blue, },
        ['@tag.attribute'] = { fg = colors.ufo_green, },
        ['@tag.delimiter'] = { fg = colors.tufts_blue, },
        -- Semantic
        ['@class'] = { fg = colors.tufts_blue },
        ['@struct'] = { fg = colors.tufts_blue },
        ['@enum'] = { fg = colors.tufts_blue },
        ['@enumMember'] = { fg = colors.violet_blue },
        ['@event'] = { fg = colors.tufts_blue },
        ['@interface'] = { fg = colors.tufts_blue },
        ['@modifier'] = { fg = colors.tufts_blue },
        ['@regexp'] = { fg = colors.banana_yellow },
        ['@typeParameter'] = { fg = colors.tufts_blue },
        ['@decorator'] = { fg = colors.tufts_blue },
        -- HTML
        htmlArg = { fg = colors.ufo_green, },
        htmlBold = { fg = colors.banana_yellow, bold = true, },
        htmlEndTag = { fg = colors.tufts_blue, },
        htmlH1 = { fg = colors.paradise_pink, },
        htmlH2 = { fg = colors.paradise_pink, },
        htmlH3 = { fg = colors.paradise_pink, },
        htmlH4 = { fg = colors.paradise_pink, },
        htmlH5 = { fg = colors.paradise_pink, },
        htmlH6 = { fg = colors.paradise_pink, },
        htmlItalic = { fg = colors.violet_blue, italic = true, },
        htmlLink = { fg = colors.violet_blue, underline = true, },
        htmlSpecialChar = { fg = colors.banana_yellow, },
        htmlSpecialTagName = { fg = colors.tufts_blue, },
        htmlTag = { fg = colors.tufts_blue, },
        htmlTagN = { fg = colors.tufts_blue, },
        htmlTagName = { fg = colors.tufts_blue, },
        htmlTitle = { fg = colors.baby_powder, },
        -- Markdown
        markdownBlockquote = { fg = colors.banana_yellow, italic = true, },
        markdownBold = { fg = colors.cadmium_orange, bold = true, },
        markdownCode = { fg = colors.ufo_green, },
        markdownCodeBlock = { fg = colors.cadmium_orange, },
        markdownCodeDelimiter = { fg = colors.cinnabar, },
        markdownH1 = { fg = colors.paradise_pink, bold = true, },
        markdownH2 = { fg = colors.paradise_pink, bold = true, },
        markdownH3 = { fg = colors.paradise_pink, bold = true, },
        markdownH4 = { fg = colors.paradise_pink, bold = true, },
        markdownH5 = { fg = colors.paradise_pink, bold = true, },
        markdownH6 = { fg = colors.paradise_pink, bold = true, },
        markdownHeadingDelimiter = { fg = colors.cinnabar, },
        markdownHeadingRule = { fg = colors.pale_cerulean, },
        markdownId = { fg = colors.violet_blue, },
        markdownIdDeclaration = { fg = colors.tufts_blue, },
        markdownIdDelimiter = { fg = colors.violet_blue, },
        markdownItalic = { fg = colors.banana_yellow, italic = true, },
        markdownLinkDelimiter = { fg = colors.violet_blue, },
        markdownLinkText = { fg = colors.paradise_pink, },
        markdownListMarker = { fg = colors.tufts_blue, },
        markdownOrderedListMarker = { fg = colors.cinnabar, },
        markdownRule = { fg = colors.pale_cerulean, },
        --  Diff
        diffAdded = { fg = colors.ufo_green, },
        diffRemoved = { fg = colors.cinnabar, },
        diffFileId = { fg = colors.banana_yellow, bold = true, reverse = true, },
        diffFile = { fg = colors.nontext, },
        diffNewFile = { fg = colors.ufo_green, },
        diffOldFile = { fg = colors.cinnabar, },
        debugPc = { bg = colors.tufts_blue, },
        debugBreakpoint = { fg = colors.cinnabar, reverse = true, },
        -- Git Signs
        GitSignsAdd = { fg = colors.bright_green, },
        GitSignsChange = { fg = colors.tufts_blue, },
        GitSignsDelete = { fg = colors.english_red, },
        GitSignsAddLn = { fg = colors.dark_gunmetal, bg = colors.bright_green, },
        GitSignsChangeLn = { fg = colors.dark_gunmetal, bg = colors.tufts_blue, },
        GitSignsDeleteLn = { fg = colors.dark_gunmetal, bg = colors.english_red, },
        GitSignsCurrentLineBlame = { fg = colors.baby_powder, },
        -- Telescope
        TelescopePromptBorder = { fg = colors.pale_cerulean, },
        TelescopeResultsBorder = { fg = colors.pale_cerulean, },
        TelescopePreviewBorder = { fg = colors.pale_cerulean, },
        TelescopeSelection = { fg = colors.baby_powder, bg = colors.selection, },
        TelescopeMultiSelection = { fg = colors.violet_blue, bg = colors.selection, },
        TelescopeNormal = { fg = colors.tufts_blue, bg = colors.dominant, },
        TelescopeMatching = { fg = colors.ufo_green, },
        TelescopePromptPrefix = { fg = colors.violet_blue, },
        -- NvimTree
        NvimTreeNormal = { fg = colors.tufts_blue, bg = colors.menu, },
        NvimTreeVertSplit = { fg = colors.dominant, bg = colors.dominant, },
        NvimTreeRootFolder = { fg = colors.tufts_blue, bold = true, },
        NvimTreeGitDirty = { fg = colors.banana_yellow, },
        NvimTreeGitNew = { fg = colors.bright_green, },
        NvimTreeImageFile = { fg = colors.paradise_pink, },
        NvimTreeFolderIcon = { fg = colors.violet_blue, },
        NvimTreeIndentMarker = { fg = colors.nontext, },
        NvimTreeEmptyFolderName = { fg = colors.pale_cerulean, },
        NvimTreeFolderName = { fg = colors.tufts_blue, },
        NvimTreeSpecialFile = { fg = colors.paradise_pink, underline = true, },
        NvimTreeOpenedFolderName = { fg = colors.tufts_blue, },
        NvimTreeCursorLine = { bg = colors.selection, },
        NvimTreeIn = { bg = colors.selection, },
        NvimTreeEndOfBuffer = endOfBuffer,
        -- NeoTree
        NeoTreeNormal = { fg = colors.baby_powder, bg = colors.dominant, },
        NeoTreeNormalNC = { fg = colors.baby_powder, bg = colors.dominant, },
        NeoTreeDirectoryName = { fg = colors.begonia },
        NeoTreeGitUnstaged = { fg = colors.cinnabar },
        NeoTreeGitModified = { fg = colors.french_lime },
        NeoTreeGitUntracked = { fg = colors.ufo_green },
        NeoTreeDirectoryIcon = { fg = colors.tufts_blue },
        NeoTreeIndentMarker = { fg = colors.nontext },
        NeoTreeDotfile = { fg = colors.pale_cerulean },
        -- Bufferline
        BufferLineIndicatorSelected = { fg = colors.violet_blue, },
        BufferLineFill = { bg = colors.dominant, },
        BufferLineBufferSelected = { bg = colors.dominant, },
        -- LSP
        DiagnosticError = { fg = colors.cinnabar, },
        DiagnosticWarn = { fg = colors.banana_yellow, },
        DiagnosticInfo = { fg = colors.tufts_blue, },
        DiagnosticHint = { fg = colors.tufts_blue, },
        DiagnosticUnderlineError = { undercurl = true, sp = colors.cinnabar, },
        DiagnosticUnderlineWarn = { undercurl = true, sp = colors.banana_yellow, },
        DiagnosticUnderlineInfo = { undercurl = true, sp = colors.tufts_blue, },
        DiagnosticUnderlineHint = { undercurl = true, sp = colors.tufts_blue, },
        DiagnosticSignError = { fg = colors.cinnabar, },
        DiagnosticSignWarn = { fg = colors.banana_yellow, },
        DiagnosticSignInfo = { fg = colors.tufts_blue, },
        DiagnosticSignHint = { fg = colors.tufts_blue, },
        DiagnosticFloatingError = { fg = colors.cinnabar, },
        DiagnosticFloatingWarn = { fg = colors.banana_yellow, },
        DiagnosticFloatingInfo = { fg = colors.tufts_blue, },
        DiagnosticFloatingHint = { fg = colors.tufts_blue, },
        DiagnosticVirtualTextError = { fg = colors.cinnabar, },
        DiagnosticVirtualTextWarn = { fg = colors.banana_yellow, },
        DiagnosticVirtualTextInfo = { fg = colors.tufts_blue, },
        DiagnosticVirtualTextHint = { fg = colors.tufts_blue, },
        LspDiagnosticsDefaultError = { fg = colors.cinnabar, },
        LspDiagnosticsDefaultWarning = { fg = colors.banana_yellow, },
        LspDiagnosticsDefaultInformation = { fg = colors.tufts_blue, },
        LspDiagnosticsDefaultHint = { fg = colors.tufts_blue, },
        LspDiagnosticsUnderlineError = { fg = colors.cinnabar, undercurl = true, },
        LspDiagnosticsUnderlineWarning = { fg = colors.banana_yellow, undercurl = true, },
        LspDiagnosticsUnderlineInformation = { fg = colors.tufts_blue, undercurl = true, },
        LspDiagnosticsUnderlineHint = { fg = colors.tufts_blue, undercurl = true, },
        LspReferenceText = { fg = colors.cadmium_orange, },
        LspReferenceRead = { fg = colors.cadmium_orange, },
        LspReferenceWrite = { fg = colors.cadmium_orange, },
        LspCodeLens = { fg = colors.tufts_blue, },
        --LSP Saga
        LspFloatWinNormal = { fg = colors.tufts_blue, },
        LspFloatWinBorder = { fg = colors.pale_cerulean, },
        LspSagaHoverBorder = { fg = colors.pale_cerulean, },
        LspSagaSignatureHelpBorder = { fg = colors.pale_cerulean, },
        LspSagaCodeActionBorder = { fg = colors.pale_cerulean, },
        LspSagaDefPreviewBorder = { fg = colors.pale_cerulean, },
        LspLinesDiagBorder = { fg = colors.pale_cerulean, },
        LspSagaRenameBorder = { fg = colors.pale_cerulean, },
        LspSagaBorderTitle = { fg = colors.menu, },
        LSPSagaDiagnosticTruncateLine = { fg = colors.pale_cerulean, },
        LspSagaDiagnosticBorder = { fg = colors.pale_cerulean, },
        LspSagaShTruncateLine = { fg = colors.pale_cerulean, },
        LspSagaDocTruncateLine = { fg = colors.pale_cerulean, },
        LspSagaLspFinderBorder = { fg = colors.pale_cerulean, },
        -- IndentBlankLine
        IndentBlanklineContextChar = { fg = colors.english_red, nocombine = true, },
        -- Nvim compe
        CmpItemAbbrDeprecated = { fg = colors.baby_powder, bg = colors.menu, },
        CmpItemAbbrMatch = { fg = colors.tufts_blue, bg = colors.menu, },
        --barbar
        BufferCurrentTarget = { fg = colors.cinnabar, },
        BufferVisibleTarget = { fg = colors.cinnabar, },
        BufferInactiveTarget = { fg = colors.cinnabar, },
        -- Compe
        CompeDocumentation = { link = "Pmenu" },
        CompeDocumentationBorder = { link = "Pmenu" },
        -- Cmp
        CmpItemKind = { link = "Pmenu" },
        CmpItemAbbr = { link = "Pmenu" },
        CmpItemKindMethod = { link = "@method" },
        CmpItemKindText = { link = "@text" },
        CmpItemKindFunction = { link = "@function" },
        CmpItemKindConstructor = { link = "@type" },
        CmpItemKindVariable = { link = "@variable" },
        CmpItemKindClass = { link = "@type" },
        CmpItemKindInterface = { link = "@type" },
        CmpItemKindModule = { link = "@namespace" },
        CmpItemKindProperty = { link = "@property" },
        CmpItemKindOperator = { link = "@operator" },
        CmpItemKindReference = { link = "@parameter.reference" },
        CmpItemKindUnit = { link = "@field" },
        CmpItemKindValue = { link = "@field" },
        CmpItemKindField = { link = "@field" },
        CmpItemKindEnum = { link = "@field" },
        CmpItemKindKeyword = { link = "@keyword" },
        CmpItemKindSnippet = { link = "@text" },
        CmpItemKindColor = { link = "DevIconCss" },
        CmpItemKindFile = { link = "TSURI" },
        CmpItemKindFolder = { link = "TSURI" },
        CmpItemKindEvent = { link = "@constant" },
        CmpItemKindEnumMember = { link = "@field" },
        CmpItemKindConstant = { link = "@constant" },
        CmpItemKindStruct = { link = "@structure" },
        CmpItemKindTypeParameter = { link = "@parameter" },
        -- navic
        NavicIconsFile = { link = "CmpItemKindFile" },
        NavicIconsModule = { link = "CmpItemKindModule" },
        NavicIconsNamespace = { link = "CmpItemKindModule" },
        NavicIconsPackage = { link = "CmpItemKindModule" },
        NavicIconsClass = { link = "CmpItemKindClass" },
        NavicIconsMethod = { link = "CmpItemKindMethod" },
        NavicIconsProperty = { link = "CmpItemKindProperty" },
        NavicIconsField = { link = "CmpItemKindField" },
        NavicIconsConstructor = { link = "CmpItemKindConstructor" },
        NavicIconsEnum = { link = "CmpItemKindEnum" },
        NavicIconsInterface = { link = "CmpItemKindInterface" },
        NavicIconsFunction = { link = "CmpItemKindFunction" },
        NavicIconsVariable = { link = "CmpItemKindVariable" },
        NavicIconsConstant = { link = "CmpItemKindConstant" },
        NavicIconsString = { link = "String" },
        NavicIconsNumber = { link = "Number" },
        NavicIconsBoolean = { link = "Boolean" },
        NavicIconsArray = { link = "CmpItemKindClass" },
        NavicIconsObject = { link = "CmpItemKindClass" },
        NavicIconsKey = { link = "CmpItemKindKeyword" },
        NavicIconsKeyword = { link = "CmpItemKindKeyword" },
        NavicIconsNull = { fg = "blue" },
        NavicIconsEnumMember = { link = "CmpItemKindEnumMember" },
        NavicIconsStruct = { link = "CmpItemKindStruct" },
        NavicIconsEvent = { link = "CmpItemKindEvent" },
        NavicIconsOperator = { link = "CmpItemKindOperator" },
        NavicIconsTypeParameter = { link = "CmpItemKindTypeParameter" },
        NavicText = { fg = 'gray' },
        NavicSeparator = { fg = 'gray' },
        -- TS rainbow colors
        rainbowcol1 = { fg = colors.cinnabar, },
        rainbowcol2 = { fg = colors.ufo_green, },
        rainbowcol3 = { fg = colors.banana_yellow, },
        rainbowcol4 = { fg = colors.violet_blue, },
        rainbowcol5 = { fg = colors.paradise_pink, },
        rainbowcol6 = { fg = colors.tufts_blue, },
        rainbowcol7 = { fg = colors.baby_powder, },
    }
end

return {
    setup = setup,
}
